### ISSUE TITLE
Practica de Desarrollo de Proyecto

### ISSUE THREAD

**Issue by FedericoVictorianoSierra** [SistemasTecTlaxiaco/proyecto-final-equipohjfe#2]
Desarrollar un proyecto funcional utilizando Visual Studio C# con la herramienta de gestor de base de datos MySql y phpMyAdmin.

Diseñar un modelo relacional con las bases de datos para definir lo siguiente:
![image](https://user-images.githubusercontent.com/71857813/171979001-ed6a6e20-4793-4b2c-a833-5cc770152550.png)
Diagrama Relacional

Tablas: Las tablas deben tener sus campos y la longitud del campo.
Definir las llaves primarias y llaves foráneas.
Definir la relaciones mediante lenguaje SQL.
2. Del Mockup que se diseño en el inicio del semestre, realizar la codificación y desarrollo del proyecto realizando las siguientes actividades.

El lenguaje para desarrollar es c#
En código fuente para desarrollar el proyecto se debe almacenar en el repositorio que se crea para su gestión.
Nota: En el repositorio se debe de programar colaborativamente que cada miembro del equipo de desarrollo deben aportar código desde su computadora local. No debe ser solo código desde una sola computadora, no se recibirá proyecto desde una sola computadora.
3. El proyecto a desarrollar debe tener una funcionalidad que realmente solucione un problema, no se puede solo programar un solo módulo. Por ejemplo un sistema funcional tiene varios módulos por ejemplo Clientes, Productos, Ventas, etc.

**Comment by FedericoVictorianoSierra** [comment]
[Practica 9 (Federico Victoriano Sierra (4US)).pdf](https://github.com/SistemasTecTlaxiaco/proyecto-final-equipohjfe/files/8836934/Practica.9.Federico.Victoriano.Sierra.4US.pdf)

**Comment by Heidi-19** [comment]
[Practica 9 - Heidi Lucy Bautista Sanjuan 4Us.pdf](https://github.com/SistemasTecTlaxiaco/proyecto-final-equipohjfe/files/8837016/Practica.9.-.Heidi.Lucy.Bautista.Sanjuan.4Us.pdf)

**Comment by EvelynLopezz** [comment]
[Practica 9 Evelyn Sugey Sanchez Lopez 4US.pdf](https://github.com/SistemasTecTlaxiaco/proyecto-final-equipohjfe/files/8837134/Practica.9.Evelyn.Sugey.Sanchez.Lopez.4US.pdf)

**Comment by JoseABCruz** [comment]
[Practica 9 (José Antonio Balbuena Cruz 4US).pdf](https://github.com/SistemasTecTlaxiaco/proyecto-final-equipohjfe/files/8837709/Practica.9.Jose.Antonio.Balbuena.Cruz.4US.pdf)

**Comment by IrvingFernand0** [comment]
Calificación:
Federico: 20%
Heidi Lucy: 20%
Evelyn Sugey: 20%
Jose Antonio: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...Felicidades...
